# Generated by Django 4.0.4 on 2022-06-04 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0006_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['content_type', 'object_id'], name='courses_fil_content_346614_idx'),
        ),
    ]
